name: vdd-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage=4.5.*
  - ddt=1.2.*
  - mock=3.0.*
  - numpy=1.16.*
  - pandas=0.24.*
  - xdg=1.0.*
  - xlrd=1.2.*
  - pip:
      - pygsheets==2.0.2
